language: php
sudo: false
install:
  - pear upgrade -f pear-1.10.5
  - pear install package.xml
php:
  - 5.6
  - 7.0
  - 7.1
matrix:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
script:
  - pear run-tests -qd tests
